### ISSUE TITLE
Not able to update the admin user via the UI

### ISSUE THREAD

**Issue by lubosmj** [pulp/pulp-ui#106]
![image](https://github.com/user-attachments/assets/0c39092a-9596-4615-85b4-6234b1fc7e82)

No logs are shown in the console. I am not able to update the admin user data. Is this expected? If so, I do not see any warning pop-up because the "Save" button is still blue.

**Comment by himdel** [comment]
confirming, https://github.com/pulp/pulp-ui/blob/main/src/containers/settings/user-profile.tsx#L116,
thanks :)

looking into making it work again, it seems user-edit does work partially
